
Epoch 1/500:   0%|          | 0/7 [00:00<?, ?it/s<class 'dict'>]Traceback (most recent call last):
  File "/storage/public/home/2008114581/zz/deeplab/train.py", line 529, in <module>
    fit_one_epoch(model_train, model, loss_history, eval_callback, optimizer, epoch, 
  File "/storage/public/home/2008114581/zz/deeplab/utils/utils_fit.py", line 24, in fit_one_epoch
    for iteration, batch in enumerate(gen):
  File "/storage/public/home/2008114581/.local/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/storage/public/home/2008114581/.local/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1328, in _next_data
    idx, data = self._get_data()
  File "/storage/public/home/2008114581/.local/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1284, in _get_data
    success, data = self._try_get_data()
  File "/storage/public/home/2008114581/.local/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1132, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/storage/public/apps/software/conda/Miniconda3-py310_23.3.1-0/lib/python3.10/queue.py", line 180, in get
    self.not_empty.wait(remaining)
  File "/storage/public/apps/software/conda/Miniconda3-py310_23.3.1-0/lib/python3.10/threading.py", line 324, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt

Epoch 1/500:   0%|          | 0/7 [00:53<?, ?it/s<class 'dict'>]
terminate called without an active exception
./train.sh: line 1: 2149066 Aborted                 (core dumped) python train.py
